In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_excel('/Users/mmeliht/Desktop/URL-Phishing-Detection/algorithms_use.xlsx')

In [3]:
df

,Reference,Year,URL Classification,Classifier / Method,Result
0,"Yuan, J., Liu, Y., Yu, L., 2021. A novel appro...",2021.0,"Malicious, Phishing\nand benign URLs",Attention-based bidirectional\nindependent rec...,99.89%
1,"Joshi, A., Lloyd, L., Westin, P., Seethapathy,...",2019.0,Malicious and\nbenign URLs,"Random Forest,","92%,"
2,NaN,NaN,NaN,"Gradient Boost,","90%,"
3,NaN,NaN,NaN,"AdaBoost,","90%,"
4,NaN,NaN,NaN,"Logistic Regression,","87%,"
5,NaN,NaN,NaN,Naive Bayes,0.7
6,"Abad, S., Gholamy, H., Aslani, M., 2023. Class...",2023.0,Malicious and\nbenign URLs,"SVM,","91.75%,"
7,NaN,NaN,NaN,"Random Forest,","92.15%,"
8,NaN,NaN,NaN,"Decision Tree,","90.18%,"
9,NaN,NaN,NaN,K-Nearest Neighbors (KNN),86.64%
10,"Aljabri, M., Alhaidari, F., Mohammad, R.M.A., ...",2022.0,Malicious and\nbenign URLs,"CNN,","95.13%,"
11,NaN,NaN,NaN,"LSTM,","95.14%,"
12,NaN,NaN,NaN,"Naïve Bayes,","96.01%,"
13,NaN,NaN,NaN,Random Forest,95.15%
14,"He, S., Li, B., Peng, H., Xin, J., Zhang, E., ...",2021.0,Malicious and\nbenign URLs,"XGBoost,","97.83%,"
15,NaN,NaN,NaN,"CS-XGBoost,","99.05%,"
16,NaN,NaN,NaN,SMOTE+XGBoost,98.43%
17,"Maci, A., Santorsola, A., Coscia, A., Iannacon...",2023.0,Malicious URLs using\nunbalanced classification,"DDQN-based classifier,\nDeep Reinforcement Lea...",93.4%
18,"DR, U.S., Patil, A., et al., 2023. Malicious u...",2023.0,"Phishing,\nbenign,\ndefacement and malware","Random Forest,","96.6%,"
19,NaN,NaN,NaN,"LightGBM,","95.6%,"
20,NaN,NaN,NaN,XGBoost,93.2%
21,"Do Xuan, C., Nguyen, H.D., Tisenko, V.N., 2020...",2020.0,Malicious and\nbenign URLs,"Random Forest,","99.77%,"
22,NaN,NaN,NaN,SVM,93.39%
23,"Patgiri, R., Katari, H., Kumar, R., Sharma, D....",2019.0,Good and bad URLs,"Random Forest,","92.38%,"
24,NaN,NaN,NaN,SVM,87.93%
25,"Tong, X., Jin, B., Wang, J., Yang, Y., Suo, Q....",2023.0,Malicious website,MM-ComBERT-LMS,98.72%
26,"Nagy, N., Aljabri, M., Shaahid, A., Ahmed, A.A...",2023.0,Phishing URLs\nthrough parallel processing,"Naïve Bayes,\nCNN,\nRandom Forest,\nLSTM",0.96
27,"Alsaedi, M., Ghaleb, F.A., Saeed, F., Ahmad, J...",2022.0,Malicious and\nbenign URLs,Random Forest,0.96
28,"Umer, M., Sadiq, S., Karamti, H., Alhebshi, R....",2022.0,Malicious and\nbenign URLs,MLP,99.62%
29,"Elsadig, M., Ibrahim, A.O., Basheer, S., Aloha...",2022.0,Phishing website,"BERT,\nNLP,\nDeep CNN\n",96.6%
30,"Abdul Samad, S.R., Balasubaramanian, S., Al-Ka...",2023.0,Phishing and benign URLs,"Random Forest,","97.44%,"
31,NaN,NaN,NaN,"Gradient Boost,","98.27%,"
32,NaN,NaN,NaN,XGBoost,98.21%
33,"Kumi, S., Lim, C., Lee, S.G., 2021. Malicious ...",2021.0,Malicious URLs\nusing data mining approach,Classification Based on Association (CBA),91.30%
34,"Roy, S.S., Awad, A.I., Amare, L.A., Erkihun, M...",2022.0,Phishing and legitimate URLs,"LSTM,","97%,"
35,NaN,NaN,NaN,"Bi-LSTM,","99%,"
36,NaN,NaN,NaN,GRU,97.5%
37,"Ashwini P, Vadivelan N D. Security from\nphish...",2021.0,"Malicious, Phishing\nand benign URLs","XGBoost,\nCS-XGBoost,\nSMOTE+XGBoost\nFNN (Fuz...",99.8%
38,"Aalla HVS, Dumpala NR, Eliazer M.\nMalicious U...",2021.0,Malicious website,"Logistic Regression,",97.5%
39,NaN,NaN,NaN,Decision Tree,0.85
40,Anil GN. Detection of phishing websites\nbased...,2020.0,Malicious and safe\nURLs,"Random forest,",86.24%
41,NaN,NaN,NaN,Single class SVM,96-97%
42,"Johnson C, Khadka B, Basnet RB, Doleck\nT. Tow...",2020.0,Malicious and\nbenign URLs,"Random forest,",96.99%
43,NaN,NaN,NaN,"fast.ai,",97.55%
44,NaN,NaN,NaN,Keras-TensorFlow(deep learning framework),93.81%
45,Chang P. Multi-layer perceptron neural\nnetwor...,2022.0,Malicious or benign\nURLs,"Logistic Regression,",93.26%
46,NaN,NaN,NaN,MLP neural network,96.35%
47,"Tariq HA, Yang W, Hameed I, Ahmed B,\nKhan RU....",2017.0,Malicious or benign\nURLs,"Multi-layer filtering model,",79.55%
48,NaN,NaN,NaN,"Naive Bayes,",77.30%
49,NaN,NaN,NaN,"Decision Tree,",79.35%
50,NaN,NaN,NaN,SVM,76.80%
51,Wang Y. Malicious URL detection an\nevaluation...,2022.0,Malicious or benign\nURLs,"Logistic regression,",92.80%
52,NaN,NaN,NaN,"SVM,",97.32%
53,NaN,NaN,NaN,"Random forest,",97.35%
54,NaN,NaN,NaN,"Gradient Boost,",96.27%
55,NaN,NaN,NaN,Bagging,97.35%
56,"Wei B, Hamad RA, Yang L, He X, Wang H,\nGao B ...",2019.0,Phishing and benign\nURLs,CNN,86.63%
57,"Hajaj C, Hason N, Dvir A. Less is more:\nrobus...",2022.0,Malware,"Logistic regression,",89.99%
58,NaN,NaN,NaN,"SVM,",96.49%
59,NaN,NaN,NaN,"ELM,",98.17%
60,NaN,NaN,NaN,ANN,97.20%
61,"Fotiadou K, Velivassaki TH, Voulkidis A,\nSkia...",2021.0,Threats and alerts\non network log by pfSense,"1D-CNN,\nLSTM",~ 99%
62,"Almuhaideb AM, Aslam N, Alabdullatif A,\nAltam...",2022.0,Phishing URLs using\nhomoglyph attack\ndetection,Random forest,99.8%
63,"Saxe J, Berlin K. eXpose: A character-level\nc...",2017.0,Intrusion detection,Expose neural network that\nuses deep learning...,97-99%
64,"Lee S, Kim J. Warningbird: detecting\nsuspicio...",2012.0,Suspicious URLs\ndetection for twitter,"Logistic regression,",87.67%
65,NaN,NaN,NaN,support vector classification (SVC),0.86
66,"Tung SP, Wong KY, Kuzminykh I, Bakhshi\nT, Ghi...",2022.0,Malicious and\nbenign URLs,"Decision Tree,",96.33%
67,NaN,NaN,NaN,Random forest,97.49%
68,"Jain AK, Gupta BB. A novel approach to\nprotec...",2016.0,Phishing and\nlegitimate sites,Auto-updated whitelist,89.38%
69,"Alsariera YA, Adeyemo VE, Balogun AO,\nAlazzaw...",2020.0,Phishing website,"AdaBoost-Extra Tree (ABET),","97.485%,"
70,NaN,NaN,NaN,Bagging –Extra tree (BET),"97.404%,"
71,NaN,NaN,NaN,"Rotation Forest – Extra Tree (RoFBET),","97.449%,"
72,NaN,NaN,NaN,LogitBoost-Extra Tree (LBET),97. 576%
73,"Liu L, Ren W, Xie F, Yi S, Yi J, Jia P.\nLearn...",2021.0,Malware and\nmalicious codes,"LSTM,","79.5%,"
74,NaN,NaN,NaN,"DCNN,","80.6%,"
75,NaN,NaN,NaN,"CNN-LSTM,","91.4%,"
76,NaN,NaN,NaN,DTCNN-LSTM,93.2%
77,"Diwan TD, Choubey S, Hota HS, Goyal\nSB, Jamal...",2021.0,Anomaly and\nmalicious traffic in\nIoT,"Feature selection based on\nchi-square, Pearso...",99.93%
78,"Wang Y, Cai W, Lyu P, Shao W. A\ncombined stat...",2018.0,Malicious browser\nextensions,"SVM,",96.52%
79,NaN,NaN,NaN,"MLP,",93.48%
80,NaN,NaN,NaN,"BN,",88.99%
81,NaN,NaN,NaN,Logistic Regression,86.16%
82,"Khan N, Abdullah J, Khan AS. Defending\nmalici...",2017.0,Malicious JavaScript\ncode,"Naive Bayes,",95.06%
83,NaN,NaN,NaN,"J48,",99.22%
84,NaN,NaN,NaN,"SVM,",94.55%
85,NaN,NaN,NaN,KNN,97.14%
86,"Zhao H, Chang Z, Bao G, Zeng X.\nMalicious dom...",2019.0,Malicious domain\nname detection,N-gram,94.04%
87,"Ispahany J, Islam R. Detecting\nmalicious urls...",2020.0,Malicious URL\nrelated to COVID-19,KNN (without entropy),99.2%
88,Yu X. Phishing websites detection based\non hy...,2020.0,Phishing website,"Logistic Regression,","95.13%,"
89,NaN,NaN,NaN,"SVM,","95.34%,"
90,NaN,NaN,NaN,"CNN,","96.87%,"
91,NaN,NaN,NaN,DBN-SVM,99.96%
92,"Rafsanjani, A. S., Kamaruddin, N. B., Behjati,...",2024.0,Malicious URL Detection,Random Forest,92.86%
93,NaN,NaN,NaN,Support Vector Machine,93.33%
94,NaN,NaN,NaN,Naive Bayes,78.53%
95,"E. Nazeeruddin, G. Latif, and N. Mohammad,\n“M...",2024.0,Malicious URL Detection and \nCategorization,Random Forest,96.4%
96,NaN,NaN,NaN,Naive Bayes,81.6%
97,NaN,NaN,NaN,Logistic Regression,83.9%
98,NaN,NaN,NaN,CNN,94.7%
99,"T. Jaswanthi, T. Harshitha, M. Belwal, and S. ...",2024.0,Binary classification,Random Forest,91.93%
100,NaN,NaN,NaN,Decision Tree,90.00%
101,NaN,NaN,NaN,Logistic Regression,66.48%
102,NaN,NaN,NaN,XGBoost,87.23%
103,NaN,NaN,NaN,Naive Bayes,31.46%
104,NaN,NaN,NaN,K-Nearest Neighbors,87.52%
105,NaN,NaN,NaN,Gradient Boosting,81.39%
106,NaN,NaN,NaN,Extra Trees,92.01%
107,"D. S. Dinakar and K. Deepak,\n“Shallow and Dee...",2024.0,Malicious URL Detection and \nCategorization,Decision Tree,99.36%
108,NaN,NaN,NaN,Random Forest,99.61%
109,NaN,NaN,NaN,Multilayer Perceptron,99.27%
110,"A. Alharbi, K. Alsubhi and R. Alotaibi, \n“Lig...",2025.0,NaN,Tiny Llama + DL,96.55
111,NaN,NaN,NaN,BERT (Base) + DL,97.5%
112,NaN,NaN,NaN,T5 (Large) + DL,97.5%
113,NaN,NaN,NaN,GPT-2 + DL,97.0%
114,"A. U. Rehman, I. Imtiaz, S. Javaid and M. Musl...",2025.0,NaN,KNN,99.77%
115,NaN,NaN,NaN,Naive Bayes,99.96%
116,NaN,NaN,NaN,Naive Bayes Kernel,99.97%
117,NaN,NaN,NaN,Random Forest,99.99%
118,NaN,NaN,NaN,Random Tree,95.38%
119,NaN,NaN,NaN,Decision Tree,99.99%
120,"Türk, F., & Kılıçaslan, M. (2025). Malicious U...",2025.0,NaN,LGM,0.96
121,NaN,NaN,NaN,XGBoost,0.96
122,NaN,NaN,NaN,Gradient Boosting,0.94
123,NaN,NaN,NaN,Random Forest,0.97
124,NaN,NaN,NaN,LSTM,0.95
125,NaN,NaN,NaN,CNN,0.95
126,NaN,NaN,NaN,CNN+LSTM,95.6%
127,NaN,NaN,NaN,GA+CNN+LSTM,0.92
128,NaN,NaN,NaN,PSO+CNN+LSTM,0.81
129,NaN,NaN,NaN,HHO+CNN+LSTM,95.7%
130,NaN,NaN,NaN,ELECTRA,0.99
131,"Onwudebelu, U., Ugah, J. O., Ezeh, S. E., & Fa...",2025.0,NaN,Logistic Regression,0.77
132,NaN,NaN,NaN,Random Forest,0.81
133,NaN,NaN,NaN,Gradient Boost,0.8
134,NaN,NaN,NaN,Hybrid (Proposed),0.84
135,"Yi, L., Omotosho, A., & Balogun, H. (2026). Ph...",2026.0,NaN,SVM,0.94
136,NaN,NaN,NaN,XGBoost,0.95
137,NaN,NaN,NaN,Naive Bayes,0.67
138,NaN,NaN,NaN,Random Forest,0.97
139,NaN,NaN,NaN,Logistic Regression,0.94
140,NaN,NaN,NaN,LightGBM,0.96
141,NaN,NaN,NaN,CatBoost,0.95

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df.columns

Index(['Reference', 'Year', 'URL Classification', 'Classifier / Method',
       'Result '],
      dtype='object')

In [6]:
df = df[['Classifier / Method','Result ']]

In [7]:
df = df.rename(columns={"Result ": "Result"})

In [8]:
df.columns

Index(['Classifier / Method', 'Result'], dtype='object')

In [9]:
df['Classifier / Method'].value_counts()

Classifier / Method
Random Forest                                                                                                9
Naive Bayes                                                                                                  6
SVM,                                                                                                         6
Random Forest,                                                                                               6
XGBoost                                                                                                      5
Logistic Regression                                                                                          5
SVM                                                                                                          4
Decision Tree                                                                                                4
Logistic Regression,                                                                                         4
Random forest,                                                                                               3
Logistic regression,                                                                                         3
CNN                                                                                                          3
LSTM,                                                                                                        3
Decision Tree,                                                                                               3
Gradient Boost,                                                                                              3
CNN,                                                                                                         2
Gradient Boosting                                                                                            2
Random forest                                                                                                2
KNN                                                                                                          2
Naive Bayes,                                                                                                 2
DBN-SVM                                                                                                      1
K-Nearest Neighbors                                                                                          1
Support Vector Machine                                                                                       1
Attention-based bidirectional\nindependent recurrent network\n(Bi-IndRNN),\nand capsule network (CapsNet)    1
KNN (without entropy)                                                                                        1
N-gram                                                                                                       1
BN,                                                                                                          1
MLP,                                                                                                         1
Feature selection based on\nchi-square, Pearson\ncorrelation, and score\ncorrelation                         1
DTCNN-LSTM                                                                                                   1
J48,                                                                                                         1
T5 (Large) + DL                                                                                              1
Extra Trees                                                                                                  1
CNN+LSTM                                                                                                     1
LightGBM                                                                                                     1
Hybrid (Proposed)                                                                                            1
Gradient Boost                                                                                               1
ELECTRA                                                                                                      1
HHO+CNN+LSTM                                                                                                 1
PSO+CNN+LSTM                                                                                                 1
GA+CNN+LSTM                                                                                                  1
LSTM                                                                                                         1
Multilayer Perceptron                                                                                        1
LGM                                                                                                          1
Random Tree                                                                                                  1
Naive Bayes Kernel                                                                                           1
GPT-2 + DL                                                                                                   1
DCNN,                                                                                                        1
BERT (Base) + DL                                                                                             1
Tiny Llama + DL                                                                                              1
CNN-LSTM,                                                                                                    1
1D-CNN,\nLSTM                                                                                                1
LogitBoost-Extra Tree (LBET)                                                                                 1
Bi-LSTM,                                                                                                     1
AdaBoost,                                                                                                    1
K-Nearest Neighbors (KNN)                                                                                    1
Naïve Bayes,                                                                                                 1
XGBoost,                                                                                                     1
CS-XGBoost,                                                                                                  1
SMOTE+XGBoost                                                                                                1
DDQN-based classifier,\nDeep Reinforcement Learning                                                          1
LightGBM,                                                                                                    1
MM-ComBERT-LMS                                                                                               1
Naïve Bayes,\nCNN,\nRandom Forest,\nLSTM                                                                     1
Random Forest                                                                                                1
MLP                                                                                                          1
BERT,\nNLP,\nDeep CNN\n                                                                                      1
Classification Based on Association (CBA)                                                                    1
GRU                                                                                                          1
Rotation Forest – Extra Tree (RoFBET),                                                                       1
XGBoost,\nCS-XGBoost,\nSMOTE+XGBoost\nFNN (Fuzzy Neural Networks)                                            1
Single class SVM                                                                                             1
fast.ai,                                                                                                     1
Keras-TensorFlow(deep learning framework)                                                                    1
MLP neural network                                                                                           1
Multi-layer filtering model,                                                                                 1
Bagging                                                                                                      1
ELM,                                                                                                         1
ANN                                                                                                          1
Expose neural network that\nuses deep learning method                                                        1
support vector classification (SVC)                                                                          1
Auto-updated whitelist                                                                                       1
AdaBoost-Extra Tree (ABET),                                                                                  1
Bagging –Extra tree (BET)                                                                                    1
CatBoost                                                                                                     1
Name: count, dtype: int64

In [10]:
df["Classifier / Method"] = df["Classifier / Method"].str.replace(r',\s*$', '', regex=True)

In [11]:
df['Classifier / Method'].value_counts()

Classifier / Method
Random Forest                                                                                                15
SVM                                                                                                          10
Logistic Regression                                                                                           9
Naive Bayes                                                                                                   8
Decision Tree                                                                                                 7
XGBoost                                                                                                       6
Random forest                                                                                                 5
CNN                                                                                                           5
LSTM                                                                                                          4
Gradient Boost                                                                                                4
Logistic regression                                                                                           3
Gradient Boosting                                                                                             2
LightGBM                                                                                                      2
KNN                                                                                                           2
MLP                                                                                                           2
K-Nearest Neighbors                                                                                           1
KNN (without entropy)                                                                                         1
Support Vector Machine                                                                                        1
DBN-SVM                                                                                                       1
Attention-based bidirectional\nindependent recurrent network\n(Bi-IndRNN),\nand capsule network (CapsNet)     1
N-gram                                                                                                        1
J48                                                                                                           1
Extra Trees                                                                                                   1
Feature selection based on\nchi-square, Pearson\ncorrelation, and score\ncorrelation                          1
DTCNN-LSTM                                                                                                    1
CNN-LSTM                                                                                                      1
BN                                                                                                            1
GPT-2 + DL                                                                                                    1
Multilayer Perceptron                                                                                         1
Tiny Llama + DL                                                                                               1
BERT (Base) + DL                                                                                              1
T5 (Large) + DL                                                                                               1
LogitBoost-Extra Tree (LBET)                                                                                  1
Naive Bayes Kernel                                                                                            1
Random Tree                                                                                                   1
LGM                                                                                                           1
CNN+LSTM                                                                                                      1
GA+CNN+LSTM                                                                                                   1
PSO+CNN+LSTM                                                                                                  1
HHO+CNN+LSTM                                                                                                  1
ELECTRA                                                                                                       1
Hybrid (Proposed)                                                                                             1
DCNN                                                                                                          1
1D-CNN,\nLSTM                                                                                                 1
Rotation Forest – Extra Tree (RoFBET)                                                                         1
GRU                                                                                                           1
AdaBoost                                                                                                      1
K-Nearest Neighbors (KNN)                                                                                     1
Naïve Bayes                                                                                                   1
CS-XGBoost                                                                                                    1
SMOTE+XGBoost                                                                                                 1
DDQN-based classifier,\nDeep Reinforcement Learning                                                           1
MM-ComBERT-LMS                                                                                                1
Naïve Bayes,\nCNN,\nRandom Forest,\nLSTM                                                                      1
Random Forest                                                                                                 1
BERT,\nNLP,\nDeep CNN\n                                                                                       1
Classification Based on Association (CBA)                                                                     1
Bi-LSTM                                                                                                       1
XGBoost,\nCS-XGBoost,\nSMOTE+XGBoost\nFNN (Fuzzy Neural Networks)                                             1
Bagging –Extra tree (BET)                                                                                     1
Single class SVM                                                                                              1
fast.ai                                                                                                       1
Keras-TensorFlow(deep learning framework)                                                                     1
MLP neural network                                                                                            1
Multi-layer filtering model                                                                                   1
Bagging                                                                                                       1
ELM                                                                                                           1
ANN                                                                                                           1
Expose neural network that\nuses deep learning method                                                         1
support vector classification (SVC)                                                                           1
Auto-updated whitelist                                                                                        1
AdaBoost-Extra Tree (ABET)                                                                                    1
CatBoost                                                                                                      1
Name: count, dtype: int64

In [12]:
# 1 Random forest → Random Forest
df.loc[df["Classifier / Method"] == "Random forest", "Classifier / Method"] = "Random Forest"

# 2 Logistic regression → Logistic Regression
df.loc[df["Classifier / Method"] == "Logistic regression", "Classifier / Method"] = "Logistic Regression"

# 3 Naïve Bayes → Naive Bayes
df.loc[df["Classifier / Method"] == "Naïve Bayes", "Classifier / Method"] = "Naive Bayes"

# 4 Support Vector Machine → SVM
df.loc[df["Classifier / Method"] == "Support Vector Machine", "Classifier / Method"] = "SVM"

# 5 support vector classification (SVC) → SVM
df.loc[df["Classifier / Method"] == "support vector classification (SVC)", "Classifier / Method"] = "SVM"

# 6 Single class SVM → SVM
df.loc[df["Classifier / Method"] == "Single class SVM", "Classifier / Method"] = "SVM"

# 7 Gradient Boost → Gradient Boosting
df.loc[df["Classifier / Method"] == "Gradient Boost", "Classifier / Method"] = "Gradient Boosting"

In [13]:
#satır sonu boşluklarını silmek için
df["Classifier / Method"] = df["Classifier / Method"].str.strip()

In [14]:
# K-Nearest Neighbors → KNN
df.loc[df["Classifier / Method"] == "K-Nearest Neighbors", "Classifier / Method"] = "KNN"

# K-Nearest Neighbors (KNN) → KNN
df.loc[df["Classifier / Method"] == "K-Nearest Neighbors (KNN)", "Classifier / Method"] = "KNN"

# KNN (without entropy) → KNN
df.loc[df["Classifier / Method"] == "KNN (without entropy)", "Classifier / Method"] = "KNN"

In [15]:
# Naive Bayes Kernel → Naive Bayes
df.loc[df["Classifier / Method"] == "Naive Bayes Kernel", "Classifier / Method"] = "Naive Bayes"

In [16]:
# Multilayer Perceptron → MLP
df.loc[df["Classifier / Method"] == "Multilayer Perceptron", "Classifier / Method"] = "MLP"

# MLP neural network → MLP
df.loc[df["Classifier / Method"] == "MLP neural network", "Classifier / Method"] = "MLP"

In [17]:
df['Classifier / Method'].value_counts()

Classifier / Method
Random Forest                                                                                                21
SVM                                                                                                          13
Logistic Regression                                                                                          12
Naive Bayes                                                                                                  10
Decision Tree                                                                                                 7
XGBoost                                                                                                       6
Gradient Boosting                                                                                             6
KNN                                                                                                           5
CNN                                                                                                           5
LSTM                                                                                                          4
MLP                                                                                                           4
LightGBM                                                                                                      2
Extra Trees                                                                                                   1
DBN-SVM                                                                                                       1
N-gram                                                                                                        1
J48                                                                                                           1
Attention-based bidirectional\nindependent recurrent network\n(Bi-IndRNN),\nand capsule network (CapsNet)     1
BN                                                                                                            1
Feature selection based on\nchi-square, Pearson\ncorrelation, and score\ncorrelation                          1
DTCNN-LSTM                                                                                                    1
BERT (Base) + DL                                                                                              1
CNN-LSTM                                                                                                      1
Tiny Llama + DL                                                                                               1
CNN+LSTM                                                                                                      1
T5 (Large) + DL                                                                                               1
GPT-2 + DL                                                                                                    1
Random Tree                                                                                                   1
LGM                                                                                                           1
LogitBoost-Extra Tree (LBET)                                                                                  1
GA+CNN+LSTM                                                                                                   1
PSO+CNN+LSTM                                                                                                  1
HHO+CNN+LSTM                                                                                                  1
ELECTRA                                                                                                       1
Hybrid (Proposed)                                                                                             1
DCNN                                                                                                          1
ANN                                                                                                           1
Rotation Forest – Extra Tree (RoFBET)                                                                         1
GRU                                                                                                           1
AdaBoost                                                                                                      1
CS-XGBoost                                                                                                    1
SMOTE+XGBoost                                                                                                 1
DDQN-based classifier,\nDeep Reinforcement Learning                                                           1
MM-ComBERT-LMS                                                                                                1
Naïve Bayes,\nCNN,\nRandom Forest,\nLSTM                                                                      1
BERT,\nNLP,\nDeep CNN                                                                                         1
Classification Based on Association (CBA)                                                                     1
Bi-LSTM                                                                                                       1
XGBoost,\nCS-XGBoost,\nSMOTE+XGBoost\nFNN (Fuzzy Neural Networks)                                             1
Bagging –Extra tree (BET)                                                                                     1
fast.ai                                                                                                       1
Keras-TensorFlow(deep learning framework)                                                                     1
Multi-layer filtering model                                                                                   1
Bagging                                                                                                       1
ELM                                                                                                           1
1D-CNN,\nLSTM                                                                                                 1
Expose neural network that\nuses deep learning method                                                         1
Auto-updated whitelist                                                                                        1
AdaBoost-Extra Tree (ABET)                                                                                    1
CatBoost                                                                                                      1
Name: count, dtype: int64

In [18]:
# DCNN → CNN
df.loc[df["Classifier / Method"] == "DCNN", "Classifier / Method"] = "CNN"

In [19]:
# LGM → LightGBM
df.loc[df["Classifier / Method"] == "LGM", "Classifier / Method"] = "LightGBM"

In [20]:
df['Classifier / Method'].value_counts()

Classifier / Method
Random Forest                                                                                                21
SVM                                                                                                          13
Logistic Regression                                                                                          12
Naive Bayes                                                                                                  10
Decision Tree                                                                                                 7
XGBoost                                                                                                       6
Gradient Boosting                                                                                             6
CNN                                                                                                           6
KNN                                                                                                           5
LSTM                                                                                                          4
MLP                                                                                                           4
LightGBM                                                                                                      3
DBN-SVM                                                                                                       1
N-gram                                                                                                        1
J48                                                                                                           1
Attention-based bidirectional\nindependent recurrent network\n(Bi-IndRNN),\nand capsule network (CapsNet)     1
BN                                                                                                            1
Feature selection based on\nchi-square, Pearson\ncorrelation, and score\ncorrelation                          1
DTCNN-LSTM                                                                                                    1
Tiny Llama + DL                                                                                               1
CNN-LSTM                                                                                                      1
Extra Trees                                                                                                   1
CNN+LSTM                                                                                                      1
BERT (Base) + DL                                                                                              1
T5 (Large) + DL                                                                                               1
GPT-2 + DL                                                                                                    1
Random Tree                                                                                                   1
Rotation Forest – Extra Tree (RoFBET)                                                                         1
GA+CNN+LSTM                                                                                                   1
PSO+CNN+LSTM                                                                                                  1
HHO+CNN+LSTM                                                                                                  1
ELECTRA                                                                                                       1
Hybrid (Proposed)                                                                                             1
LogitBoost-Extra Tree (LBET)                                                                                  1
ELM                                                                                                           1
Bagging –Extra tree (BET)                                                                                     1
AdaBoost-Extra Tree (ABET)                                                                                    1
AdaBoost                                                                                                      1
CS-XGBoost                                                                                                    1
SMOTE+XGBoost                                                                                                 1
DDQN-based classifier,\nDeep Reinforcement Learning                                                           1
MM-ComBERT-LMS                                                                                                1
Naïve Bayes,\nCNN,\nRandom Forest,\nLSTM                                                                      1
BERT,\nNLP,\nDeep CNN                                                                                         1
Classification Based on Association (CBA)                                                                     1
Bi-LSTM                                                                                                       1
GRU                                                                                                           1
XGBoost,\nCS-XGBoost,\nSMOTE+XGBoost\nFNN (Fuzzy Neural Networks)                                             1
fast.ai                                                                                                       1
Keras-TensorFlow(deep learning framework)                                                                     1
Multi-layer filtering model                                                                                   1
Bagging                                                                                                       1
ANN                                                                                                           1
1D-CNN,\nLSTM                                                                                                 1
Expose neural network that\nuses deep learning method                                                         1
Auto-updated whitelist                                                                                        1
CatBoost                                                                                                      1
Name: count, dtype: int64

In [21]:
df.loc[
    df["Classifier / Method"].str.contains(
        r"DBN-SVM|CNN-LSTM|CNN\+LSTM|DTCNN-LSTM|GA\+CNN\+LSTM|PSO\+CNN\+LSTM|HHO\+CNN\+LSTM",
        na=False
    ),
    "Classifier / Method"
] = "Hybrid Deep Learning Models"

In [28]:
#en çok kullanılan 10 algoritma
df["Classifier / Method"].value_counts().head(10)

Classifier / Method
Random Forest                  21
SVM                            13
Logistic Regression            12
Naive Bayes                    10
Hybrid Deep Learning Models     7
Decision Tree                   7
Gradient Boosting               6
CNN                             6
XGBoost                         6
KNN                             5
Name: count, dtype: int64

In [29]:
df

                                   Classifier / Method    Result
0    Attention-based bidirectional\nindependent rec...    99.89%
1                                        Random Forest      92%,
2                                    Gradient Boosting      90%,
3                                             AdaBoost      90%,
4                                  Logistic Regression      87%,
5                                          Naive Bayes       0.7
6                                                  SVM   91.75%,
7                                        Random Forest   92.15%,
8                                        Decision Tree   90.18%,
9                                                  KNN    86.64%
10                                                 CNN   95.13%,
11                                                LSTM   95.14%,
12                                         Naive Bayes   96.01%,
13                                       Random Forest    95.15%
14                                             XGBoost   97.83%,
15                                          CS-XGBoost   99.05%,
16                                       SMOTE+XGBoost    98.43%
17   DDQN-based classifier,\nDeep Reinforcement Lea...     93.4%
18                                       Random Forest    96.6%,
19                                            LightGBM    95.6%,
20                                             XGBoost     93.2%
21                                       Random Forest   99.77%,
22                                                 SVM    93.39%
23                                       Random Forest   92.38%,
24                                                 SVM    87.93%
25                                      MM-ComBERT-LMS    98.72%
26            Naïve Bayes,\nCNN,\nRandom Forest,\nLSTM      0.96
27                                       Random Forest      0.96
28                                                 MLP    99.62%
29                               BERT,\nNLP,\nDeep CNN     96.6%
30                                       Random Forest   97.44%,
31                                   Gradient Boosting   98.27%,
32                                             XGBoost    98.21%
33           Classification Based on Association (CBA)    91.30%
34                                                LSTM      97%,
35                                             Bi-LSTM      99%,
36                                                 GRU     97.5%
37   XGBoost,\nCS-XGBoost,\nSMOTE+XGBoost\nFNN (Fuz...     99.8%
38                                 Logistic Regression     97.5%
39                                       Decision Tree      0.85
40                                       Random Forest    86.24%
41                                                 SVM    96-97%
42                                       Random Forest    96.99%
43                                             fast.ai    97.55%
44           Keras-TensorFlow(deep learning framework)    93.81%
45                                 Logistic Regression    93.26%
46                                                 MLP    96.35%
47                         Multi-layer filtering model    79.55%
48                                         Naive Bayes    77.30%
49                                       Decision Tree    79.35%
50                                                 SVM    76.80%
51                                 Logistic Regression    92.80%
52                                                 SVM    97.32%
53                                       Random Forest    97.35%
54                                   Gradient Boosting    96.27%
55                                             Bagging    97.35%
56                                                 CNN    86.63%
57                                 Logistic Regression    89.99%
58                                                 SVM    96.49%
59                                                 ELM    98.17%
60                                                 ANN    97.20%
61                                       1D-CNN,\nLSTM     ~ 99%
62                                       Random Forest     99.8%
63   Expose neural network that\nuses deep learning...    97-99%
64                                 Logistic Regression    87.67%
65                                                 SVM      0.86
66                                       Decision Tree    96.33%
67                                       Random Forest    97.49%
68                              Auto-updated whitelist    89.38%
69                          AdaBoost-Extra Tree (ABET)  97.485%,
70                           Bagging –Extra tree (BET)  97.404%,
71               Rotation Forest – Extra Tree (RoFBET)  97.449%,
72                        LogitBoost-Extra Tree (LBET)  97. 576%
73                                                LSTM    79.5%,
74                                                 CNN    80.6%,
75                         Hybrid Deep Learning Models    91.4%,
76                         Hybrid Deep Learning Models     93.2%
77   Feature selection based on\nchi-square, Pearso...    99.93%
78                                                 SVM    96.52%
79                                                 MLP    93.48%
80                                                  BN    88.99%
81                                 Logistic Regression    86.16%
82                                         Naive Bayes    95.06%
83                                                 J48    99.22%
84                                                 SVM    94.55%
85                                                 KNN    97.14%
86                                              N-gram    94.04%
87                                                 KNN     99.2%
88                                 Logistic Regression   95.13%,
89                                                 SVM   95.34%,
90                                                 CNN   96.87%,
91                         Hybrid Deep Learning Models    99.96%
92                                       Random Forest    92.86%
93                                                 SVM    93.33%
94                                         Naive Bayes    78.53%
95                                       Random Forest     96.4%
96                                         Naive Bayes     81.6%
97                                 Logistic Regression     83.9%
98                                                 CNN     94.7%
99                                       Random Forest    91.93%
100                                      Decision Tree    90.00%
101                                Logistic Regression    66.48%
102                                            XGBoost    87.23%
103                                        Naive Bayes    31.46%
104                                                KNN    87.52%
105                                  Gradient Boosting    81.39%
106                                        Extra Trees    92.01%
107                                      Decision Tree    99.36%
108                                      Random Forest    99.61%
109                                                MLP    99.27%
110                                    Tiny Llama + DL     96.55
111                                   BERT (Base) + DL     97.5%
112                                    T5 (Large) + DL     97.5%
113                                         GPT-2 + DL     97.0%
114                                                KNN    99.77%
115                                        Naive Bayes    99.96%
116                                        Naive Bayes    99.97%
117                                      Random Forest    99.99%
118                                        Random Tree    95.38%
119                                      Decision Tree    99.99%
120                                           LightGBM      0.96
121                                            XGBoost      0.96
122                                  Gradient Boosting      0.94
123                                      Random Forest      0.97
124                                               LSTM      0.95
125                                                CNN      0.95
126                        Hybrid Deep Learning Models     95.6%
127                        Hybrid Deep Learning Models      0.92
128                        Hybrid Deep Learning Models      0.81
129                        Hybrid Deep Learning Models     95.7%
130                                            ELECTRA      0.99
131                                Logistic Regression      0.77
132                                      Random Forest      0.81
133                                  Gradient Boosting       0.8
134                                  Hybrid (Proposed)      0.84
135                                                SVM      0.94
136                                            XGBoost      0.95
137                                        Naive Bayes      0.67
138                                      Random Forest      0.97
139                                Logistic Regression      0.94
140                                           LightGBM      0.96
141                                           CatBoost      0.95