In [1]:
import pandas as pd

In [2]:
df_phishing = pd.read_csv('C:/Users/USER/Desktop/URL-Phishing-Detection/datasets/Phishing_URL_dataset/Phishing_URLs.csv')

In [3]:
df_legitimate = pd.read_csv('C:/Users/USER/Desktop/URL-Phishing-Detection/datasets/Phishing_URL_dataset/URL_dataset.csv')

In [4]:
####################### Extract Features and Feature Engineer ####################

In [5]:
df_phishing.head(10)

                                                 url      Type
0  https://docs.google.com/presentation/d/e/2PACX...  Phishing
1    https://btttelecommunniccatiion.weeblysite.com/  Phishing
2                        https://kq0hgp.webwave.dev/  Phishing
3  https://brittishtele1bt-69836.getresponsesite....  Phishing
4         https://bt-internet-105056.weeblysite.com/  Phishing
5                         https://teleej.weebly.com/  Phishing
6          https://maryleyshon.wixsite.com/my-site-1  Phishing
7           https://chamakhman.wixsite.com/my-site-4  Phishing
8                          https://posts-ch.buzz/ch/  Phishing
9                       https://tinyurl.com/bdfpfyur  Phishing

In [6]:
df_legitimate.head(10)

                         url        type
0     https://www.google.com  legitimate
1    https://www.youtube.com  legitimate
2   https://www.facebook.com  legitimate
3      https://www.baidu.com  legitimate
4  https://www.wikipedia.org  legitimate
5     https://www.reddit.com  legitimate
6      https://www.yahoo.com  legitimate
7   https://www.google.co.in  legitimate
8         https://www.qq.com  legitimate
9     https://www.amazon.com  legitimate

In [7]:
df_legitimate.columns

Index(['url', 'type'], dtype='object')

In [8]:
df_phishing.columns

Index(['url', 'Type'], dtype='object')

In [9]:
df_legitimate['type'].value_counts()

type
legitimate    345738
phishing      104438
Name: count, dtype: int64

In [10]:
df_phishing['Type'].value_counts()

Type
Phishing    54807
Name: count, dtype: int64

In [11]:
df_legitimate.rename(columns={"type": "Label"}, inplace=True)
df_phishing.rename(columns={"Type": "Label"}, inplace=True)

In [12]:
# Label sütununu 1 ve 0 haline getiriyoruz.
df_phishing["Label"] = df_phishing["Label"].map({
    "Phishing": 1
})

In [13]:
df_phishing['Label'].value_counts()

Label
1    54807
Name: count, dtype: int64

In [14]:
# Label sütununu 1 ve 0 haline getiriyoruz.
df_legitimate["Label"] = df_legitimate["Label"].map({
    "legitimate": 0,
    "phishing": 1
})

In [15]:
df_legitimate['Label'].value_counts()

Label
0    345738
1    104438
Name: count, dtype: int64

In [16]:
df = pd.concat([df_legitimate, df_phishing], ignore_index=True)

In [17]:
df.shape

(504983, 2)

In [18]:
df.drop_duplicates(subset="url", inplace=True)

In [19]:
df.shape

(504933, 2)

In [20]:
df['Label'].value_counts()

Label
0    345738
1    159195
Name: count, dtype: int64

In [21]:
df.isna().sum()

url      0
Label    0
dtype: int64

In [22]:
(df["url"].astype(str).str.contains(" ")).sum()

np.int64(517)

In [23]:
(df["url"].astype(str) != df["url"].astype(str).str.strip()).sum()

np.int64(1)

In [24]:
df = df[~df["url"].astype(str).str.contains(" ")]
df = df.reset_index(drop=True)

In [25]:
df.shape

(504416, 2)

In [26]:
# End Of Data Sets Concad

In [27]:
# Extract Features Start


 # Uzunluk & Domain
 "LengthOfURL",
 "DomainLengthOfURL",
 "TLDLength",
 "IsDomainIP

 # Karakter & Yapı
 "DigitCntInURL",
 "EqualCharCntInURL",
 "QuesMarkCntInURL",
 "OtherSpclCharCntInURL",
 "URLLetterRatio",
 "HavingPath",
 "HavingAnchor",
 "PathLength

 # Matematiksel / Metin Karmaşıklığı
 "ShannonEntropy",
 "FractalDimension",
 "KolmogorovComplexity",
 "HexPatternCnt",
 "Base64PatternCnt

 # Hedef
 "Label

In [28]:
#LengthOfURL
df["LengthOfURL"] = df["url"].astype(str).apply(len)

In [33]:
df.head()

                         url  Label  LengthOfURL  DomainLengthOfURL
0     https://www.google.com      0           22                 14
1    https://www.youtube.com      0           23                 15
2   https://www.facebook.com      0           24                 16
3      https://www.baidu.com      0           21                 13
4  https://www.wikipedia.org      0           25                 17

In [29]:
#DomainLengthOfURL
#Domain içinde [.] ifadesi olduğu için domain uzunluğunu bulmada hata veriyor. Bu ifadeyi kaldırdık.
def check_bad_urls(x):
    try:
        urlparse(x)
        return False
    except:
        return True

df[df["url"].astype(str).apply(check_bad_urls)]

                                                      url  Label  LengthOfURL
0                                  https://www.google.com      0           22
1                                 https://www.youtube.com      0           23
2                                https://www.facebook.com      0           24
3                                   https://www.baidu.com      0           21
4                               https://www.wikipedia.org      0           25
...                                                   ...    ...          ...
504411  http://www.balajigloves.net/js/attiinnddeexxxb...      1           52
504412                      http://lookatmynewphotos.com/      1           29
504413  https://www.markdbeats.com/wp-content/plugins/...      1           52
504414              http://webmailadmin0.myfreesites.net/      1           37
504415       http://www.habbocreditosparati.blogspot.com/      1           44

[504416 rows x 3 columns]

In [30]:
df["url"] = df["url"].astype(str).str.replace(r"\[\.\]", ".", regex=True)

In [31]:
from urllib.parse import urlparse
df["DomainLengthOfURL"] = df["url"].apply(
    lambda x: len(urlparse(x).netloc)
)

In [32]:
df.head()

                         url  Label  LengthOfURL  DomainLengthOfURL
0     https://www.google.com      0           22                 14
1    https://www.youtube.com      0           23                 15
2   https://www.facebook.com      0           24                 16
3      https://www.baidu.com      0           21                 13
4  https://www.wikipedia.org      0           25                 17